name: fume_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch=2.1.0
  - pytorch::torchvision=0.16.0
  - pytorch::pytorch-cuda=12.1
  - numpy=1.24.3
  - pandas=2.0.3
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - scikit-learn=1.3.0
  - scikit-image=0.21.0
  - opencv=4.8.0
  - pillow=10.0.0
  - tqdm=4.65.0
  - pyyaml=6.0
  - pip=23.2.1
  - pip:
      - wandb==0.15.12
      - albumentations==1.3.1
      - segmentation-models-pytorch==0.3.3
      - timm==0.9.7
      - tensorboard==2.14.0
      - plotly==5.17.0
      - ipywidgets==8.1.1
      - jupyter==1.0.0
      - ipykernel==6.25.2
